CREATE DATABASE burgers_db;
USE burgers_db;

CREATE TABLE burgers (
id INTEGER(11) NOT NULL AUTO_INCREMENT,
burger_name VARCHAR(250) NOT NULL,
devoured boolean NOT NULL DEFAULT FALSE,
date TIMESTAMP NOT NULL,
PRIMARY KEY (id)
);